### ISSUE TITLE
Uncaught TypeError: Cannot read property 'types' of undefined

### ISSUE THREAD

**Issue by zuhair-naqvi** [skevy/graphiql-app#12]
When I launch the app and point to a valid graphql endpoint i get:

TypeError: Cannot read property 'types' of undefined
    at Object.r (file:///Users/zuhairnaqvi/Downloads/GraphiQL.app/Contents/Resources/app/dist/bundle.js:31:10486)
    at file:///Users/zuhairnaqvi/Downloads/GraphiQL.app/Contents/Resources/app/dist/bundle.js:20:14843

The endpoint is working when used directly.

**Comment by skevy** [comment]
That's very strange. I haven't seen this one. There shouldn't be anything in this app that would cause that particular issue (though I could be mistaken)...have you tried with the latest version of normal ol' GraphiQL?

**Comment by skevy** [comment]
Closing due to inactivity.
