### ISSUE TITLE
Problem during installation 

### ISSUE THREAD

**Issue by FcoCrespo** [skevy/graphiql-app#163]
Hello, I have the next problem during the installation in the step npm run build

C:\Users\Crespo\graphiql-app>npm run build

> graphiql-app@0.7.2 build C:\Users\Crespo\graphiql-app
> webpack --config webpack/webpack.config.production.js --progress --profile --colors

3309ms build modules
6ms seal
1ms optimize
213ms build modules
12ms hashing
24ms create chunk assets
1234ms additional chunk assets
1ms optimize chunk assets
1ms optimize assets
Hash: 4ca67fdfccd8255be49e
Version: webpack 1.15.0
Time: 4819ms
    + 588 hidden modules

ERROR in ./~/graphql-language-service-parser/dist/onlineParser.js
Module parse failed: C:\Users\Crespo\graphiql-app\node_modules\graphql-language-service-parser\dist\onlineParser.js Unexpected token (128:24)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (128:24)
    at Parser.pp$4.raise (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseIdent (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:2189:12)
    at Parser.pp$3.parsePropertyName (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:2052:101)
    at Parser.pp$3.parseObj (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:1988:14)
    at Parser.pp$3.parseExprAtom (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:1805:19)
    at Parser.pp$3.parseExprSubscripts (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:1608:25)
    at Parser.pp$3.parseExpression (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:1573:21)
    at Parser.pp$1.parseStatement (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:727:47)
    at Parser.pp$1.parseBlock (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:2105:24)
    at Parser.pp$1.parseFunction (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:1065:10)
    at Parser.pp$1.parseFunctionStatement (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:818:17)
    at Parser.pp$1.parseStatement (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:694:19)
    at Parser.pp$1.parseTopLevel (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Users\Crespo\graphiql-app\node_modules\webpack\lib\Parser.js:902:15)
    at NormalModule.<anonymous> (C:\Users\Crespo\graphiql-app\node_modules\webpack\lib\NormalModule.js:104:16)
    at NormalModule.onModuleBuild (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at C:\Users\Crespo\graphiql-app\node_modules\webpack\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
 @ ./~/graphql-language-service-parser/dist/index.js 15:21-46

ERROR in bundle.js from UglifyJs
SyntaxError: Unexpected token: name (CharacterStream) [./~/graphql-language-service-parser/dist/CharacterStream.js:3,0]
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules

**Comment by dmitry-ts** [comment]
Experienced same issue

**Comment by erangakm** [comment]
getting the same issue as well. anyone has any clue why this could be hapenning?

**Comment by ahmadabastomi** [comment]
same issue

**Comment by aiswaryajami** [comment]
Has this ever been resolved. Its 2023 and am getting the same error. some threads mentioned a fix was deployed and this issue is not seen anymore in 2019 but looks like its still happening.
