### ISSUE TITLE
brew version broken?

### ISSUE THREAD

**Issue by akeating** [skevy/graphiql-app#25]
First thing I see when launching the version installed by homebrew today is:
```
TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
    at TypeError (native)
    at Object.graphQLFetcher [as fetcher] (file:///opt/homebrew-cask/Caskroom/graphiql/0.3.1/GraphiQL.app/Contents/Resources/app/dist/bundle.js:18:1115)
    at t._fetchQuery (file:///opt/homebrew-cask/Caskroom/graphiql/0.3.1/GraphiQL.app/Contents/Resources/app/dist/bundle.js:20:17540)
    at t.componentDidMount (file:///opt/homebrew-cask/Caskroom/graphiql/0.3.1/GraphiQL.app/Contents/Resources/app/dist/bundle.js:20:14765)
    at r.o.notifyAll (file:///opt/homebrew-cask/Caskroom/graphiql/0.3.1/GraphiQL.app/Contents/Resources/app/dist/bundle.js:1:21680)
    at r.d.close (file:///opt/homebrew-cask/Caskroom/graphiql/0.3.1/GraphiQL.app/Contents/Resources/app/dist/bundle.js:17:15585)
    at r.i.closeAll (file:///opt/homebrew-cask/Caskroom/graphiql/0.3.1/GraphiQL.app/Contents/Resources/app/dist/bundle.js:1:27910)
    at r.i.perform (file:///opt/homebrew-cask/Caskroom/graphiql/0.3.1/GraphiQL.app/Contents/Resources/app/dist/bundle.js:1:27366)
    at v (file:///opt/homebrew-cask/Caskroom/graphiql/0.3.1/GraphiQL.app/Contents/Resources/app/dist/bundle.js:2:16420)
    at r.i.perform (file:///opt/homebrew-cask/Caskroom/graphiql/0.3.1/GraphiQL.app/Contents/Resources/app/dist/bundle.js:1:27283)
```

**Comment by akeating** [comment]
Ah I think this refers to an invalid endpoint.
