### ISSUE TITLE
I'm having the following error neither GET or POST work

### ISSUE THREAD

**Issue by sibelius** [skevy/graphiql-app#34]
```
TypeError: Failed to fetch
    at TypeError (native)
    at graphQLFetcher (GraphiQL.app/Contents/Resources/app/dist/bundle.js:18:27042)
    at t.value (GraphiQL.app/Contents/Resources/app/dist/bundle.js:21:12301)
    at t.value (GraphiQL.app/Contents/Resources/app/dist/bundle.js:21:7330)
    at r.notifyAll (GraphiQL.app/Contents/Resources/app/dist/bundle.js:2:20781)
    at r.close (GraphiQL.app/Contents/Resources/app/dist/bundle.js:17:28887)
    at r.closeAll (GraphiQL.app/Contents/Resources/app/dist/bundle.js:2:24083)
    at r.perform (GraphiQL.app/Contents/Resources/app/dist/bundle.js:2:23529)
    at u (GraphiQL.app/Contents/Resources/app/dist/bundle.js:18:21581)
    at r.perform (GraphiQL.app/Contents/Resources/app/dist/bundle.js:2:23446)
```

**Comment by GuillaumeLeclerc** [comment]
Are you sure your endpoint is up and running ?

**Comment by sibelius** [comment]
yep, it is up and running

**Comment by sibelius** [comment]
I'm using El Captation macosx

**Comment by sibelius** [comment]
it was missing `https://` before graphql endpoint

it should throw a better error though

**Comment by linjunpop** [comment]
That's really confusing.
