### ISSUE TITLE
npm run start error

### ISSUE THREAD

**Issue by Mifrill** [skevy/graphiql-app#65]
```
npm run start

> graphiql-app@0.5.0 start /media/sf_PUBLIC/graphiql-app-0.5.1
> electron .

err:module:import_dll Library UIAutomationCore.DLL (which is needed by L"Z:\\media\\sf_PUBLIC\\graphiql-app-0.5.1\\node_modules\\electron-prebuilt\\dist\\electron.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\media\\sf_PUBLIC\\graphiql-app-0.5.1\\node_modules\\electron-prebuilt\\dist\\electron.exe" failed, status c0000135
npm ERR! code ELIFECYCLE
npm ERR! errno 53
npm ERR! graphiql-app@0.5.0 start: `electron .`
npm ERR! Exit status 53
npm ERR! 
npm ERR! Failed at the graphiql-app@0.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mifrill/.npm/_logs/2017-06-11T12_33_51_380Z-debug.log
```
2017-06-11T12_33_51_380Z-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle graphiql-app@0.5.0~prestart: graphiql-app@0.5.0
6 silly lifecycle graphiql-app@0.5.0~prestart: no script for prestart, continuing
7 info lifecycle graphiql-app@0.5.0~start: graphiql-app@0.5.0
8 verbose lifecycle graphiql-app@0.5.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle graphiql-app@0.5.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/media/sf_PUBLIC/graphiql-app-0.5.1/node_modules/.bin:/home/mifrill/.rbenv/bin:/home/mifrill/bin:/home/mifrill/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
10 verbose lifecycle graphiql-app@0.5.0~start: CWD: /media/sf_PUBLIC/graphiql-app-0.5.1
11 silly lifecycle graphiql-app@0.5.0~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle graphiql-app@0.5.0~start: Returned: code: 53  signal: null
13 info lifecycle graphiql-app@0.5.0~start: Failed to exec start script
14 verbose stack Error: graphiql-app@0.5.0 start: `electron .`
14 verbose stack Exit status 53
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid graphiql-app@0.5.0
16 verbose cwd /media/sf_PUBLIC/graphiql-app-0.5.1
17 verbose Linux 4.4.0-79-generic
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
19 verbose node v8.0.0
20 verbose npm  v5.0.0
21 error code ELIFECYCLE
22 error errno 53
23 error graphiql-app@0.5.0 start: `electron .`
23 error Exit status 53
24 error Failed at the graphiql-app@0.5.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 53, true ]
```

**Comment by skevy** [comment]
Were you ever able to get this working?

**Comment by Mifrill** [comment]
Trying to build from oficial source to linux led to this result
I used other sources (https://github.com/jaaaco/graphiql-app/releases/tag/v0.5.1b) 
it was success and tests successfully pass, But graphical interface did not work: 
https://monosnap.com/file/IdJLDzf3VDQFoDBQo7yYsQBs4W80Jn
So fow now i use graphiql-app-win32-x64.zip from non official realese source code on OS Windows

By the way, the previous official release (0.5.0) can be build from the sources on Linux, but the result will be the same (the tests pass, and the graphical interface does not work)
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by skevy** [comment]
I'm not sure why this would happen.

I'm able to build and run the app on my mac, as well as build the release versions for Linux. If you're able to fix this and want to send a PR, I'd be happy to accept it.

For now I'm going to close this issue, however.
