### ISSUE TITLE
install with brew, when open give error  

### ISSUE THREAD

**Issue by webmobiles** [skevy/graphiql-app#82]
When i open the app, i get this error
```
TypeError: Failed to fetch
    at TypeError (native)
    at e.graphQLFetcher (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:23:29032)
    at t.value (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:26:30092)
    at Object.handleRunQuery [as onRun] (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:27:140)
    at n._onClick (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:32:19610)
    at Object.r (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:7:3561)
    at a (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:7:1902)
    at Object.u [as executeDispatchesInOrder] (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:7:2117)
    at d (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:6:30536)
    at v (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:6:30662)
```

when i try to execute querys i get:

`SyntaxError: Unexpected token < in JSON at position 1`

**Comment by erikfrisk** [comment]
I get the same error.

**Comment by FergusZhou** [comment]
+1

**Comment by webmobiles** [comment]
it's better this repo, server und client working :

https://github.com/jferrettiboke/react-auth-app-example

**Comment by Skaronator** [comment]
Got the same issue. Installed `graphiql-app-setup-0.6.1.exe` on W10.

**Comment by selfagency** [comment]
same here on high sierra

```
TypeError: Failed to fetch
    at TypeError (native)
    at e.graphQLFetcher (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:23:29032)
    at t.value (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:26:29129)
    at t.value (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:26:22695)
    at e.notifyAll (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:7:12508)
    at r.close (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:23:4786)
    at r.closeAll (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:7:15916)
    at r.perform (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:7:15405)
    at u (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:23:22899)
    at r.perform (file:///Applications/GraphiQL.app/Contents/Resources/app.asar/dist/bundle.js:7:15322)
```

**Comment by samlevin** [comment]
Same here (high sierra)
